### ISSUE TITLE
Not able to format vscode's settings.json

### ISSUE THREAD

**Issue by ronakg** [j-brooke/FracturedJsonVSC#1] opened 2021-06-30 21:27 UTC
I get an error `Unexpected token: in JSON at position X` when trying to format the vscode's `settings.json` file. The error appears irrespective of size of the block I'm trying to format - a few lines vs the whole file.

Example:

```json
    "vim.argumentObjectClosingDelimiters": [
        ")",
        "]",
        "}"
    ],
    "vim.argumentObjectOpeningDelimiters": [
        "(",
        "[",
        "{"
    ],
```

Error: `Unexpected token: in JSON at position 37`.

**Comment by j-brooke** [comment] 2021-06-30 22:48
I suspect the issue is comments.

Will you please save a copy of your file and check a few things?
1. Does the status bar in the lower right say "JSON" or "JSON with Comments"?
2. If there are comments, can FractureJson format the document once they're removed?

VSCode unfortunately plays some dirty tricks with the JSON standard.  Comments were deliberately excluded from the JSON standard as a design choice, according to [Wikipedia](https://en.wikipedia.org/wiki/JSON).

"jsonc" is a derived format that allows comments.  That's what VSCode uses for its `settings.json` file.  In most cases, if you open up a `*.json` file in VSCode, it's treated as pure JSON and you get red squiggles under the comments.  It looks like VSCode must have special-case handling for its own important files (like `settings.json`, `launch.json`, etc.) to open them with the "jsonc" editor instead.

It might be possible to rewrite the formatter using [Microsoft's jsonc parser](https://github.com/Microsoft/node-jsonc-parser) instead of the built-in Javascript JSON parser.  There are likely some challenges in deciding what the correct reformatting behavior should be, though.

**Comment by ronakg** [comment] 2021-06-30 22:52
> Does the status bar in the lower right say "JSON" or "JSON with Comments"?

It says "JSON with Comments" but I do not have any comments in my `settings.json`. I even changed the file type to just JSON and I don't see any errors in the file. 

> If there are comments, can FractureJson format the document once they're removed?

There are no comments and still see the same error when I try to format the file.

**Comment by j-brooke** [comment] 2021-07-01 14:08
Would it be possible to post the whole file?  Maybe a Github Gist?  (Of course, make sure it doesn't have sensitive data in it first.)

One thing that I didn't document is that the "Format JSON Selection" command requires the selection to be a well-formed JSON element on its own, after skipping leading and trailing whitespace and commas.  So for instance it's expected to work if you select 1 item from a list, but not if you select 2 items.  

That doesn't explain why it would be failing for you with the whole document selected.  But I wonder if an incremental testing approach might give us more insight.  For instance:
1. Select `"("` and invoke Format JSON Selection.  It shouldn't do anything, but shouldn't give an error.
2. Select `["(", "[", "{"]` and invoke Format JSON Selection.  It should put them all on one line.
3. Select whatever object this property value is from, and invoke Format JSON Selection.  See what happens.  (That selection should include the opening and closing braces of the object).
...

By the way, interestingly, if you have `settings.json` open and you switch from "JSON with Comments" to "JSON", it still doesn't put squiggles under comments.  But if you use a copy of the file, even if it's saved in the same directory, switching to the "JSON" type will cause it to flag comments as errors.  I assume this was a hack that the VS team had to make for backward compatibility reasons.

**Comment by ronakg** [comment] 2021-07-01 20:11
I found the issue. It was an extra comma `,` on the last item of the JSON object. VS Code allows that extra comma but it's not part of the JSON format.

**Comment by j-brooke** [comment] 2021-07-02 00:04
Glad you found the root of it.  Looks like there's nothing to be done here.  Closing.

**Closed as completed by j-brooke** 2021-07-02 00:04 UTC
