### ISSUE TITLE
Fails upon encountering some control character in JSON

### ISSUE THREAD

**Issue by KraXen72** [j-brooke/FracturedJsonVSC#12] opened 2023-12-25 16:50 UTC
```json
{
 "title": "Mádrová | Gábri - Mirinof | Mádr"
}
```
i get an error:
```
FracturedJson: Control characters are not allowed in strings at row=2, col=27
```
The Deno language Server can format it just fine, but i like FracturedJSON's output better. 
Can you please fix it? Thanks!

**Comment by j-brooke** [comment] 2023-12-25 20:19
I think the important character may have been lost when you pasted your example to GitHub.  The character that looks like it's causing trouble is showing as "�" to me.  When I paste it into VSCode as UTF-16LE and view it with a hex editor, it's showing as `\uFFFD`, which is Unicode's designated "replacement character".

If possible, will you please give me the hex version, and let me know which encoding you're using?

If it is in fact a control character, then it's not allowed by the JSON standard.  But there may be some disagreement between FracturedJson, Unicode, and JSON about what constitutes a control character.

The other possibility that I see is that it's a Unicode codepoint that requires surrogate pairs.  I suspect the code isn't handling those correctly.

**Comment by KraXen72** [comment] 2023-12-26 09:03
i generate this json from a script, which gets the info from XML files. some of them are in the windows-(some numbers) encoding instead of utf-8.
i should probably sanitize the strings in the script, but i need to find some good typescript library for that (any reccomendations?)
i don't really know how to send the hex version, and sending the whole json is not viable, since it contains some names of people and info i don't know if i can share.

**Comment by j-brooke** [comment] 2023-12-26 19:02
Does your script specify which encoding you're reading from?  If the file is Windows-1252 (or whatever) but the code assumes it's UTF-8, it might be interpreting some of the real printable characters as control characters before it's written as JSON.

As an experiment, if it's not too much of a hassle, it might be interesting to try this experiment:

* Identify one of the XML files that, when converted to JSON, gives you trouble in FracturedJson.
* Open a copy of the XML file in VSCode.  If necessary, do a "reopen with encoding" by clicking on the encoding in the status bar.
* Do "save with encoding" by clicking on the encoding in the status bar and choose UTF-8.
* Run your script on that file to convert it to JSON.
* Check whether FJ is still giving you errors.

If that solves the problem, then I would guess the problem is with your conversion script.  (If so, you can probably use the `TextDecoder` class to convert.  Or maybe the UNIX command `iconv` to pre-convert the files.)

If that doesn't solve the problem, then I'd suggest looking at the hex version of the JSON file with a VSCode hex extension like this one: https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor

**Comment by KraXen72** [comment] 2023-12-28 11:37
i can conduct this experiment later, however, i think the formatting shouldn't fail either way - either treat the invalid character as valid and show a warning, but complete formatting, or remove the invalid char (possibly a setting for this behaviour?)

**Comment by KraXen72** [comment] 2023-12-28 11:37
i can conduct this experiment later, however, i think the formatting shouldn't fail either way - either treat the invalid character as valid and show a warning, but complete formatting, or remove the invalid char (possibly a setting for this behaviour?)

**Comment by j-brooke** [comment] 2024-01-21 14:42
Without a case to reproduce the problem, there's nothing to be done here.  I'm closing this issue.  But it's certainly something to watch out for in the future.

**Closed as completed by j-brooke** 2024-01-21 14:42 UTC

**Comment by KraXen72** [comment] 2024-01-21 19:36
okay. I'll comment here if i do the experiment you suggested. Thanks!
